-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema librarydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `librarydb` ;

-- -----------------------------------------------------
-- Schema librarydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `librarydb` DEFAULT CHARACTER SET utf8 ;
USE `librarydb` ;

-- -----------------------------------------------------
-- Table `book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book` ;

CREATE TABLE IF NOT EXISTS `book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `author_first_name` VARCHAR(20) NOT NULL,
  `author_last_name` VARCHAR(20) NOT NULL,
  `publish_year` YEAR(4) NOT NULL,
  `publisher` VARCHAR(45) NULL DEFAULT NULL,
  `Series` VARCHAR(50) NULL DEFAULT 'N/A',
  `occurrence_in_series` INT NULL DEFAULT 0,
  `medium` VARCHAR(20) NULL DEFAULT NULL,
  `number_of_pages` INT NULL DEFAULT NULL,
  `synopsis` TEXT(2500) NULL DEFAULT NULL,
  `book_cover` TEXT(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS bookborrower@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'bookborrower'@'localhost' IDENTIFIED BY 'bookborrower';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'bookborrower'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `book`
-- -----------------------------------------------------
START TRANSACTION;
USE `librarydb`;
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (1, 'Tailchaser\'s Song', 'Tad', 'Williams', 1985, 'DAW Books', 'N/A', 0, 'Paperback', 364, 'A young tomcat named Tailchaser leaves the comfort of our world for a mysterious forest when the cat he cares for most goes missing. Soon he discovers the secret world of cats, learns of his special heritage, and confronts an evil cat god.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1328382008i/23340.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (2, 'The Dragonbone Chair', 'Tad', 'Williams', 1988, 'DAW Books', 'Memory, Sorrow and Thorn', 1, 'Paperback', 766, 'Simon, a young kitchen boy and magician\'s apprentice, whose dreams of great deeds and heroic wars come all too shockingly true when his world is torn apart by a terrifying civil war. A war fueled by ancient hatreds, immortal enemies, and the dark powers of sorcery.', 'https://m.media-amazon.com/images/I/510HkSGJ6oL._SL350_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (3, 'Stone of Farewell', 'Tad', 'Williams', 1990, 'DAW Books', 'Memory, Sorrow and Thorn', 2, 'Paperback', 727, 'Josua and the remaining few survivors from the attack on Naglimund are fleeing for their lives from the Norns. Both parties end up concluding that they must travel to the Stone of Farewell, an ancient place that may retain power from the Sithi.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1441754723i/28689.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (4, 'To Green Angel Tower', 'Tad', 'Williams', 1993, 'DAW Books', 'Memory, Sorrow and Thorn', 3, 'Paperback', 1593, 'As the Storm King\'s power grows, the loyal allies of Prince Josua struggle to rally their forces at the Stone of Farewell. There, Simon and the surviving members of the League of the Scroll attempt to unravel a prophecy that may ultimately allow them to strike down the undead Storm King and bring peace to the kingdom. This epic saga concludes as Simon travels back to castle Hayholt to confront Ineluki.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1347824309i/28691.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (5, 'Shadowmarch', 'Tad', 'Williams', 2004, 'DAW Books', 'Shadowmarch', 1, 'Hardback', 642, 'Tensions wrack the court of Southmarch Castle. King Olin has been captured by the bandit rulers of Hierosol in the distant south and is being held for ransom, but raising the money is beggaring the kingdom. Olin\'s heir Prince Kendrick is trying to hold the country together whilst his younger twin siblings, Barrick and Briony, have their own problems to face.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1290856030i/28694.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (6, 'Shadowplay', 'Tad', 'Williams', 2007, 'DAW Books', 'Shadowmarch', 2, 'Hardback', 641, 'King Olin Eddon is a prisoner in a faraway land. Olin\'s heir Kendrick is dead - slain by treachery and dark, bloody magic - and Kendric\'s younger brother and sister have barely escaped several attempts on their own lives.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1442582884i/28687.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (7, 'Shadowrise', 'Tad', 'Williams', 2010, 'DAW Books', 'Shadowmarch', 3, 'Hardback', 554, 'With King Olin imprisoned and Prince Kendrick slain, the royal twins Barrick and Briony have been forced to flee their homeland. But both families and nations can hide dark and terrible secrets.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1442890367i/6661489.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (8, 'Shadowheart', 'Tad', 'Williams', 2010, 'DAW Books', 'Shadowmarch', 4, 'Hardback', 722, 'Southmarch Castle is about to be caught between two implacable enemies, the ancient, immortal Qar and the insane god-king, the Autarch of Xis. Meanwhile, its two young defenders, Princess Briony and Prince Barrick, are both trapped far away from home and fighting for their lives.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388201685i/7876746.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (9, 'Pawn of Prophecy', 'David', 'Eddings', 1982, 'Del Rey Books', 'The Belgariad', 1, 'Paperback', 262, 'Long ago, the evil God Torak fought a war to obtain an object of immense power - the Orb of Aldur. But Torak was defeated and the Orb reclaimed by Belgarath, the sorcerer. Garion, a young farm lad, loves the story when he first hears it from the old storyteller. But it has nothing to do with him. Or does it? For the stories also tell of a prophecy that must be fulfilled - a destiny handed down through the generations. And Torak is stirring again...', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1391346857i/44659.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (10, 'Queen of Sorcery', 'David', 'Eddings', 1982, 'Del Rey Books', 'The Belgariad', 2, 'Paperback', 327, 'Legends tell how Belgarath the sorcerer and his daughter Polgara defeated the evil God Torak, imprisoning him in an endless sleep. But now a priest of Torak is racing to his God with the Orb of Aldur and is racing to reawaken him. Belgarath and Polgara are on his trail. With them is Garion, a simple farm boy only months before. And with each league the group travel, the power of sorcery is growing in Garion...', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1428943169i/587582.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (11, 'Magician\'s Gambit', 'David', 'Eddings', 1983, 'Del Rey Books', 'The Belgariad', 3, 'Paperback', 307, 'Many thousands of years ago, two prophecies came into being and a moment was fixed, when only one would determine the future. This moment, a clash between the maimed god Torak and the descendant of the Rivan king, is approaching...Garion, was brought up as a farm lad but is now beginning to understand the extent of his part in the prophecy, and working hard to control his sorcerous power. He is travelling towards this meeting in a sinister tower where the evil god lies sleeping. With him is the wise sorcerer Belgarath. And Ce\'Nedra - a wilful young princess who refuses to believe in sorcery, but is terrified that Garion will die in the coming confrontation...', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1315276590i/44688.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (12, 'Castle of Wizardry', 'David', 'Eddings', 1984, 'Del Rey Books', 'The Belgariad', 4, 'Paperback', 375, 'Garion and his companions now have the Orb of Aldur, carried by an innocent young boy, and must return it to its rightful home on the pommel of the sword in the Great Hall on the island of Riva. As they journey across the lands, Murgo soldiers and Grolim sorcerers try to stop them. But Garion\'s true adversary, the evil God Torak - is waking up in his dark tomb - ready for the final conflict.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1421711682i/645023.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (13, 'Enchanter\'s End Game', 'David', 'Eddings', 1984, 'Del Rey Books', 'The Belgariad', 5, 'Paperback', 372, 'Come, Belgarion, Child of Light. I await thee in the City of Night ...\' A confrontation that has been prophesied for thousands of years is racing towards a conclusion. For as Garion comes into his heritage as the Rivan King, Overlord of the West, and takes up the Orb of Aldur to protect the land, Torak awakes and his evil hordes of Murgo soldiers and Grolim priests march in his name. While the princess Ce\'Nedra mobilises the forces of the free lands to repel the invaders, Garion heads for his duel with Torak - a duel upon which the fate of the whole world depends...', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1217735909i/44687.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (14, 'Rhapsody', 'Elizabeth', 'Haydon', 1999, 'Tor Fantasy', 'Symphony of Ages', 1, 'Paperback', 656, 'Rhapsody is a woman, a Singer of some talent, who is swept up into events of world-shattering import. On the run from an old romantic interest who won\'t take no for an answer, Rhapsody literally bumps into a couple of shady characters: half-breeds who come to her rescue in the nick of time.', 'https://m.media-amazon.com/images/I/51Q6XXSZAZL._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (15, 'Prophecy', 'Elizabeth', 'Haydon', 2000, 'Tor Fantasy', 'Symphony of Ages', 2, 'Paperback', 697, 'Driven by a prophetic vision, Rhapsody races to rescue a religious leader while Achmed and Grunthor seek the F\'dor--an ancient and powerful demon. These companions may be destined to fulfill The Prophecy of the Three, but their time is running short. They must find their elusive enemy before his darkness consumes them all.', 'https://m.media-amazon.com/images/I/51ohoOvBr+L._SL350_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (16, 'Destiny', 'Elizabeth', 'Haydon', 2001, 'Tor Fantasy', 'Symphony of Ages', 3, 'Paperback', 835, 'Driven by prophetic visions, the three know that time is running short, know that they must find their elusive enemy before his darkness consumes them all. But after their final, brutal confrontation with the F\'dor, their world crosses the threshold of disaster and faces utter oblivion. The action reaches a fevered pitch, achieving a crescendo of tragedy, love, and triumph of human spirit over world-shattering cataclysm.', 'https://pictures.abebooks.com/isbn/9780312867508-us.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (17, 'Requiem for the Sun', 'Elizabeth', 'Haydon', 2002, 'Tor Fantasy', 'Symphony of Ages', 4, 'Paperback', 587, 'It has been three years since their devastating battle, and peace has settled across their land. But to the south an empire lies ready to crumble. When the Dowager Empress dies, along with her successor, a great war breaks out, threatening to overwhelm the known world.', 'https://pictures.abebooks.com/isbn/9780312878849-us.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (18, 'Elegy for a Lost Star', 'Elizabeth', 'Haydon', 2004, 'Tor Fantasy', 'Symphony of Ages', 5, 'Paperback', 427, 'The dragon Anwyn--who has lain for three years in deathlike sleep in a grave of rock and black coal is freed by the cataclysm that concluded REQUIEM FOR THE SUN. sisoriented and confused, she remembers only two things-the person who trapped her in dragon form and locked her in the grave-Rhapsody-and an all-encompassing desire to wreak vengeance.', 'https://m.media-amazon.com/images/I/51SZV3+QN4L._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (19, 'The Assassin King', 'Elizabeth', 'Haydon', 2006, 'Tor Fantasy', 'Symphony of Ages', 6, 'Paperback', 415, 'The Assassin King opens at winter\'s end with the arrival by sea of a mysterious hunter, a man of ancient race and purpose, who endlessly chants the names of the pantheon of demons that are his intended victims, as well as one other: Ysk, the original name of the Brother, now known as Achmed, the Assassin King of Ylorc.', 'https://m.media-amazon.com/images/I/81qlyO1oL7L._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (20, 'The Assassin\'s Blade', 'Sarah J.', 'Maas', 2014, 'Bloomsbury', 'Throne of Glass', 0, 'Paperback', 435, 'Celaena Sardothien is her kingdom\'s most feared assassin. Though she works for the powerful and ruthless Assassin\'s Guild, Celaena yields to no one and trusts only her fellow killer for hire, Sam.', 'https://m.media-amazon.com/images/I/81KTUX7JTcL._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (21, 'Throne of Glass', 'Sarah J.', 'Maas', 2012, 'Bloomsbury', 'Throne of Glass', 1, 'Paperback', 404, 'Throne of Glass is about an eighteen year old girl named Celaena Sardothien. Celaena is a trained assassin who is serving a life sentence for killing hundreds of people. One day Celaena gets offered a deal by young Captain Westfall: her freedom in return for a huge sacrifice.', 'https://m.media-amazon.com/images/I/81DW1r3CIwL._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (22, 'Crown of Midnight', 'Sarah J.', 'Maas', 2013, 'Bloomsbury', 'Throne of Glass', 2, 'Paperback', 418, 'Celaena has earned her spot as King\'s Champion but feels no loyalty toward the cruel King of Ardalan. She continues to try to unravel the secrets that lurk in the glass castle, risking the relationships she\'s building and her life.', 'https://m.media-amazon.com/images/I/815izKnNL+L._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (23, 'Heir of Fire', 'Sarah J.', 'Maas', 2014, 'Bloomsbury', 'Throne of Glass', 3, 'Paperback', 562, 'Celaena has survived deadly contests and shattering heartbreak-but at an unspeakable cost. Now, she must travel to a new land to confront her darkest truth…a truth about her heritage that could change her life-and her future-forever.', 'https://m.media-amazon.com/images/I/81QaOS36qXL._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (24, 'Queen of Shadows', 'Sarah J.', 'Maas', 2015, 'Bloomsbury', 'Throne of Glass', 4, 'Paperback', 645, 'An assassin turned Queen, after realising her identity as Aelin Galathyius, heir to Terrasen; she will stop at nothing to overthrow the King, free her people and reclaim her home. To do so she must battle her friends, save her foes and face her demons. Only by risking everything may it be possible for her to succeed.', 'https://m.media-amazon.com/images/I/81pDre-+0ML._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (25, 'Empire of Storms', 'Sarah J.', 'Maas', 2016, 'Bloomsbury', 'Throne of Glass', 5, 'Paperback', 689, 'The long path to the throne has only just begun for Aelin Galathynius as war looms on the horizon. Loyalties have been broken and bought, friends have been lost and gained, and those who possess magic find themselves at odds with those who don\'t.', 'https://m.media-amazon.com/images/I/81b65wz8f6L._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (26, 'Tower of Dawn', 'Sarah J.', 'Maas', 2017, 'Bloomsbury', 'Throne of Glass', 6, 'Paperback', 660, 'After enduring unspeakable horrors as a child, Yrene Towers has no desire to help a young lord from Adarlan, let alone heal him. yet she has sworn an oath to assist those in need – and will honor it. But Lord Westfall carries darkness from his own past, and Yrene soon comes to realize it could engulf them both.', 'https://m.media-amazon.com/images/I/91pmqiTzBhL._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (27, 'Kingdom of Ash', 'Sarah J.', 'Maas', 2018, 'Bloomsbury', 'Throne of Glass', 7, 'Paperback', 980, 'Aelin Galathynius\'s journey from slave to king\'s assassin to the queen of a once-great kingdom reaches its heart-rending finale as war erupts across her world. . . Aelin has risked everything to save her people-but at a tremendous cost.', 'https://m.media-amazon.com/images/I/81kkr85m+OL._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (28, 'A Court of Thorns and Roses', 'Sarah J.', 'Maas', 2015, 'Bloomsbury', 'A Court of Thorns and Roses', 1, 'Hardback', 416, 'When nineteen-year-old huntress Feyre kills a wolf in the woods, a terrifying creature arrives to demand retribution. Dragged to a treacherous magical land she knows about only from legends, Feyre discovers that her captor is not truly a beast, but one of the lethal, immortal faeries who once ruled her world.', 'https://m.media-amazon.com/images/I/81Z-yHX8OcL._AC_UF1000,1000_QL80_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (29, 'A Court of Mist and Fury', 'Sarah J.', 'Maas', 2016, 'Bloomsbury', 'A Court of Thorns and Roses', 2, 'Hardback', 624, 'As Feyre navigates its dark web of politics, passion, and dazzling power, a greater evil looms—and she might be key to stopping it. But only if she can harness her harrowing gifts, heal her fractured soul, and decide how she wishes to shape her future—and the future of a world cleaved in two.', 'https://i5.walmartimages.com/asr/b4437d89-746c-4de0-bf49-19055bb82e2a_1.0310ac58d9e1b9a90bc5c1e33560eb32.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (30, 'A Court of Wings and Ruin', 'Sarah J.', 'Maas', 2017, 'Bloomsbury', 'A Court of Thorns and Roses', 3, 'Hardback', 711, 'Feyre was married in secret to Rhysand and is now High Lady of the Night Court. She returns as a spy to the Spring Court with Tamlin, pretending that she had been brainwashed into staying with Rhysand in the Night Court for all those months. Secretly, Feyre is seething with anger and plots revenge.', 'https://i5.walmartimages.com/asr/f4fa9fb1-b4b5-49ea-97c8-c59ad1a43c48_1.c32c6fde15bd02369563c4c63cf87a2f.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (31, 'A Court of Frost and Starlight', 'Sarah J.', 'Maas', 2018, 'Bloomsbury', 'A Court of Thorns and Roses', 4, 'Hardback', 229, 'Feyre, Rhysand, and their friends are still busy rebuilding the Night Court and the vastly altered world beyond, recovering from the war that changed everything. But Winter Solstice is finally approaching, and with it, the joy of a hard-earned reprieve. Yet even the festive atmosphere can\'t keep the shadows of the past from looming. As Feyre navigates her first Winter Solstice as High Lady, her concern for those dearest to her deepens. They have more wounds than she anticipated--scars that will have a far-reaching impact on the future of their court.', 'https://pictures.abebooks.com/isbn/9781681196312-us.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (32, 'A Court of Silver Flames', 'Sarah', 'Maas', 2021, 'Bloomsbury', 'A Court of Thorns and Roses', 5, 'Hardback', 751, 'Nesta Archeron has always been prickly-proud, swift to anger, and slow to forgive. And ever since being forced into the Cauldron and becoming High Fae against her will, she\'s struggled to find a place for herself within the strange, deadly world she inhabits. Worse, she can\'t seem to move past the horrors of the war with Hybern and all she lost in it.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1602570691i/53138095.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (33, 'Eragon', 'Christopher', 'Paolini', 2003, 'Knopf', 'Inheritance', 1, 'Hardback', 497, 'When Eragon finds a polished blue stone in the forest, he thinks it is the lucky discovery of a poor farm boy; perhaps it will buy his family meat for the winter. But when the stone brings a dragon hatchling, Eragon soon realizes he has stumbled upon a legacy nearly as old as the Empire itself.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1366212852i/113436.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (34, 'Eldest', 'Christopher', 'Paolini', 2005, 'Knopf', 'Inheritance', 2, 'Hardback', 668, 'Darkness falls…despair abounds…evil reigns…Eragon and his dragon, Saphira, have just saved the rebel state from destruction by the mighty forces of King Galbatorix, cruel ruler of the Empire. Now Eragon must travel to Ellesmera, land of the elves, for further training in the skills of the Dragon Rider.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1387119654i/45978.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (35, 'Brisingr', 'Christopher', 'Paolini', 2008, 'Knopf', 'Inheritance', 3, 'Hardback', 748, 'Oaths sworn... loyalties tested... forces collide. It\'s been only months since Eragon first uttered \"brisingr\", an ancient language term for fire. Since then, he\'s not only learned to create magic with words — he\'s been challenged to his very core. Following the colossal battle against the Empires warriors on the Burning Plains, Eragon and his dragon, Saphira, have narrowly escaped with their lives. Still, there is more adventure at hand for the Rider and his dragon, as Eragon finds himself bound by a tangle of promises he may not be able to keep.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1661030683i/2248573.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (36, 'Inheritance', 'Christopher', 'Paolini', 2011, 'Knopf', 'Inheritance', 4, 'Hardback', 849, 'It began with Eragon... It ends with Inheritance. Not so very long ago, Eragon — Shadeslayer, Dragon Rider — was nothing more than a poor farm boy, and his dragon, Saphira, only a blue stone in the forest. Now the fate of an entire civilization rests on their shoulders.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1390886502i/7664041.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (37, 'The Fork, the Witch, and the Worm', 'Christopher', 'Paolini', 2018, 'Knopf', 'Tales from Alagaesia', 1, 'Hardback', 266, 'It\'s been a year since Eragon departed Alagaësia in search of the perfect home to train a new generation of Dragon Riders. Now he is struggling with an endless sea of tasks: constructing a vast dragonhold, wrangling with suppliers, guarding dragon eggs, and dealing with belligerent Urgals and haughty elves.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1539186315i/26152839.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (38, 'The Hobbit', 'J.R.R.', 'Tolkien', 1937, 'Ballantine Books', 'N/A', 0, 'Paperback', 305, 'The Hobbit is set in Middle-earth and follows home-loving Bilbo Baggins, the titular hobbit, who joins the wizard Gandalf and thirteen dwarves that make up Thorin Oakenshield\'s Company, on a quest to reclaim the dwarves\' home and treasure from the dragon Smaug.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546071216i/5907.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (39, 'The Fellowship of the Ring', 'J.R.R.', 'Tolkien', 1954, 'Ballantine Books', 'The Lord of the Rings', 1, 'Paperback', 458, 'When the eccentric hobbit Bilbo Baggins leaves his home in the Shire, he gives his greatest treasure to his heir Frodo: a magic ring that makes its wearer invisible. Because of the difficulty Bilbo has in giving the ring away, his friend the wizard Gandalf the Grey suspects that the ring is more than it appears.', 'https://m.media-amazon.com/images/I/51C1V6CS3ML._SX314_BO1,204,203,200_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (40, 'The Two Towers', 'J.R.R.', 'Tolkien', 1954, 'Ballantine Books', 'The Lord of the Rings', 2, 'Paperback', 398, 'Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go.', 'https://m.media-amazon.com/images/I/510TRFMAR8L._SL350_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (41, 'The Return of the King', 'J.R.R.', 'Tolkien', 1955, 'Ballantine Books', 'The Lord of the Rings', 3, 'Paperback', 466, 'The Dark Lord has risen, and as he unleashes hordes of Orcs to conquer all Middle-earth, Frodo and Sam struggle deep into his realm in Mordor. To defeat Sauron, the One Ring must be destroyed in the fires of Mount Doom. But the way is impossibly hard, and Frodo is weakening. The Ring corrupts all who bear it and Frodo’s time is running out.', 'https://mythologyoftolkien.files.wordpress.com/2017/03/return-of-the-king.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (42, 'The Amulet of Samarkand', 'Jonathan', 'Stroud', 2003, 'Hyperion', 'The Bartimaeus Trilogy', 1, 'Hardback', 462, 'Nathaniel is a 12-year-old magician in training in an alternate London where magic is real and perilous creatures and artifacts abound. Bartimaeus is a cocky, 5,000-year-old djinni whom Nathaniel summons to help him get revenge against an arrogant adult wizard.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1528705815i/334123.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (43, 'The Golem\'s Eye', 'Jonathan', 'Stroud', 2004, 'Hyperion', 'The Bartimaeus Trilogy', 2, 'Hardback', 562, 'A seemingly invulnerable clay golem is making random attacks on London. Nathaniel and the all-powerful, totally irreverent djinni, Bartimaeus, must travel to Prague to discover the source of the golem\'s power.', 'https://m.media-amazon.com/images/I/51T92YKBQ4L._SL350_.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (44, 'Ptolemy\'s Gate', 'Jonathan', 'Stroud', 2006, 'Hyperion', 'The Bartimaeus Trilogy', 3, 'Hardback', 501, 'In Alexandria in 125 B.C., Bartimaeus, a demon known as a djinn, saves his current master, Ptolemy, from four assassins. In modern day London, the British government is facing chaos. They sent troops to America to put down rebellion there.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1528705796i/59264.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (45, 'The Ring of Solomon', 'Jonathan', 'Stroud', 2010, 'Hyperion', 'A Bartimaeus Novel', 1, 'Hardback', 398, 'It is 950 B.C.E., and King Solomon rules Jerusalem with a steely hand; a hand on which gleams a magic ring of immense and unforgiving power. Solomon has just begun work on his marvelous temple, charging Khaba, a formidable magician in his royal court, to oversee its construction. The workforce is an ill-behaved bunch of demons, a particularly unruly djinni named Bartimaeus among them.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348894736i/7640705.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (46, 'Inkheart', 'Cornelia', 'Funke', 2003, 'Chicken House', 'Inkheart Trilogy', 1, 'Hardback', 534, 'One cruel night, Meggie\'s father reads aloud from a book called INKHEART-- and an evil ruler escapes the boundaries of fiction and lands in their living room. Suddenly, Meggie is smack in the middle of the kind of adventure she has only read about in books. Meggie must learn to harness the magic that has conjured this nightmare. For only she can change the course of the story that has changed her life forever.', 'https://www.pluggedin.com/wp-content/uploads/2020/01/inkheart-cover-image.jpeg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (47, 'Inkspell', 'Cornelia', 'Funke', 2005, 'Chicken House', 'Inkheart Trilogy', 2, 'Hardback', 635, 'Although a year has passed, not a day goes by without Meggie thinking of INKHEART, the book whose characters became real. But for Dustfinger, the fire-eater brought into being from words, the need to return to the tale has become desperate. When he finds a crooked storyteller with the ability to read him back, Dustfinger leaves behind his young apprentice Farid and plunges into the medieval world of his past. Distraught, Farid goes in search of Meggie, and before long, both are caught inside the book, too. But the story is threatening to evolve in ways neither of them could ever have imagined.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1395358683i/28195.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (48, 'Inkdeath', 'Cornelia', 'Funke', 2007, 'Chicken House', 'Inkheart Trilogy', 3, 'Hardback', 663, 'The Adderhead--his immortality bound in a book by Meggie\'s father, Mo--has ordered his henchmen to plunder the villages. The peasants\' only defense is a band of outlaws led by the Bluejay--Mo\'s fictitious double, whose identity he has reluctantly adopted. But the Book of Immortality is unraveling, and the Adderhead again fears the White Women of Death. To bring the renegade Bluejay back to repair the book, the Adderhead kidnaps all the children in the kingdom, dooming them to slavery in his silver mines unless Mo surrends. First Dustfinger, now Mo: Can anyone save this cursed story?', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327341991i/2325825.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (49, 'The Thief Lord', 'Cornelia', 'Funke', 2000, 'Chicken House', 'N/A', 0, 'Paperback', 345, 'Two orphaned children are on the run, hiding among the crumbling canals and misty alleyways of the city of Venice. Befriended by a gang of street children and their mysterious leader, the Thief Lord, they shelter in an old, disused cinema. On their trail is a bungling detective, obsessed with disguises and the health of his pet tortoises. But a greater threat to the boys\' new-found freedom is something from a forgotten past – a beautiful magical treasure with the power to spin time itself.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327960342i/113304.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (50, 'Redwall', 'Brian', 'Jacques', 1986, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 333, 'Redwall Abbey, tranquil home to a community of peace-loving mice, is threatened by Cluny the Scourge savage bilge rat warlord and his battle-hardened horde. But the Redwall mice and their loyal woodland friends combine their courage and strength.', 'https://m.media-amazon.com/images/I/51eOqMpYExL.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (51, 'Mossflower', 'Brian', 'Jacques', 1998, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 373, 'The clever and greedy wildcat Tsarmina becomes ruler of all Mossflower Woods and is determined to govern the peaceful woodlanders with an iron paw. The brave mouse Martin and quick-talking mouse thief Gonff meet in the depths of Kotir Castle\'s dungeon. The two escape and resolve to end Tsarmina\'s tyrannical rule. Joined by Kinny the mole, Martin and Gonff set off on a dangerous quest for Salamandastron, where they are convinced that their only hope, Boar the Fighter, still lives.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1281811805i/201341.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (52, 'Mattimeo', 'Brian', 'Jacques', 1990, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 432, 'Preparation for a great feast are underway at Redwall Abbey, and the young mouse Mattimeo is contributing his share of the labors. But Mattimeo is the son of Matthias, the guardian of Redwall Abbey, and it is this fact that makes him the target of a fiendish kidnapping plot contrived by the vicious fox, Slagar the Cruel. When Matthias and his brave followers abandon their homes and face enslavement for the return of their children, the captive Mattimeo stands to prove his worth--and an unexpected hero is born.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388194271i/201342.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (53, 'Mariel of Redwall', 'Brian', 'Jacques', 1991, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 370, 'A mouse-ship is attacked by the pirate rat Gabool and his heinous band of cut-throats. Hapless voyagers Mariel and her father Joseph the Bellmaker are mercilessly thrown into the sea by the pirates. Mariel washes ashore, starved and near death, and is taken in by the hospitable inhabitants of Redwall Abbey. Sure that her poor father is dead, Mariel swears an oath of vengeance against the filthy pirates who killed her father. With he help of a motley band of animals, Mariel leads the charge to recover a bell and avenge her father.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1299761476i/7993.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (54, 'Salamandastron', 'Brian', 'Jacques', 1992, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 356, 'The inhabitants of Redwall relax in the haze of summer-but as they do, the neighboring stronghold of Salamandastron lies besieged by the evil weasel army of Ferhago the Assassin. Worse still, Mara, beloved daughter of Urthstripe, Badger Lord of the Fire Mountain, is in terrible danger. Then a lightning bolt uncovers the sword of Martin the Warrior, and young Samkin embarks on an adventure that leads him to Mara. Can the good creatures triumph over the villainous Assassin?', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1386924804i/7983.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (55, 'Martin the Warrior', 'Brian', 'Jacques', 1993, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 376, 'As a child, Martin was brought to the stronghold of Badrang the Tyrant, forced into enslavement behind its massive walls. But he was strong. He was brave. And mere escape was not his plan as long as his father’s sword rested in Badrang’s ruthless fist…', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327877608i/201345.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (56, 'The Bellmaker', 'Brian', 'Jacques', 1994, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 397, 'It has been four seasons since Mariel, the warrior-mouse daughter of Joseph the Bellmaker, and her companion, Dandin, set off from Redwall to fight evil in Mossflower. Nothing has been heard of them since. Then one night, in a dream, the legendary Martin the Warrior comes to the Bellmaker with a mysterious message. Clearly, Mariel and Dandin are in grave danger. Joseph and four Redwallers set off at once to aid them. As they push over land and sea, they cannot know the terrible threats they face. Will the Bellmaker and his companions arrive in time to help Mariel and Dandin?', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1386921177i/7979.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (57, 'The Outcast of Redwall', 'Brian', 'Jacques', 1996, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 367, 'Many seasons ago, the evil ferret warlord known as Swartt Sixclaw abandoned his infant son and left him for dead.... Raised among the good creatures of Redwall Abbey,the ferret Veil could never escape his fathers tainted blood. And when he committed an unforgivable crime, Veil was banished from abbey forever..... Now sixclaw and his vicious though raised by the good creatures of Redwall Abbey, the young ferret Veil was cast father is leading hordes of sea rats and vermin on the warpath, and Veil must choose his destiny- as a friend or foe of Redwall Abbey...', 'https://static.wikia.nocookie.net/redwall/images/1/1d/OoRPaperback.jpg/revision/latest?cb=20060208140458');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (58, 'Pearls of Lutra', 'Brian', 'Jacques', 1996, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 351, 'The Tears of All Oceans are missing. Six magnificent rose-colored pearls, which inspire passion and greed in all who see them, have been stolen and passed from hand to hand, leaving a cryptic trail of death and deception in their wake. And now Ublaz Mad Eyes, the evil emperor of a tropical isle, is determined to let no one stand in the way of his desperate attempt to claim the pearls as his own. At Redwall Abbey, a young hedgehog maid, Tansy, is equally determined to find the pearls first, with the help of her friends. And she must succeed, for the life of the one she holds dear is in great danger...', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388786457i/7980.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (59, 'The Long Patrol', 'Brian', 'Jacques', 1997, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 318, 'The murderous Rapscallion army is on the move. Dealt a humiliating defeat by Lady Cregga Rose Eyes, the Badger Lady of Salamandastron, who still pursues them, the Rapscallions are heading inland to take an even greater the peaceful Abbey of Redwall. The elite fighting unit of hares, the Long Patrol, is called out to draw them off. At the forefront is the young hare Tammo, the lead sword in one of the most ferocious battles Redwall has ever faced.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1437625105i/7981.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (60, 'Marlfox', 'Brian', 'Jacques', 1998, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 365, 'A villainous new presence is aprowl in Mossflower Woods-the Marlfoxes. Stealthy and mysterious, they are out to plunder and destroy everything in their path. And when they reach Redwall Abbey, they ruthlessly steal the most precious treasure of all-the tapestry of Martin the Warrior. It takes Dann Reguba and Song Swifteye, children of warrior squirrels, to follow in their fathers\' heroic footsteps. Together with the young shrew Dippler, and Burble the brave watervole, they embark upon the seemingly impossible quest. . . .', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1311702426i/7999.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (61, 'The Legend of Luke', 'Brian', 'Jacques', 1999, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 340, 'Journey back in time to the days before Redwall, revealing with dramatic poignancy the legend of the first of the magnificent Redwall warriors--Luke, father of Martin. It is that legend Martin hopes to discover when he embarks on a perilous journey to the northland shore, where his father abandoned him as a child. There, within the carcass of a great red ship he uncovers what he has been searching for: the story of the evil Pirate stoat, Vilu Daskar, and the valiant mousewarrior who pursued him relentlessly over the high seas, seeking to destroy Vilu at all costs, even if it meant deserting his only son. Brian Jacques reaches a new pinnacle in storytelling, imparting the story behind the story of the greatest Redwall warrior of them all.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1442546166i/7987.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (62, 'Lord Brocktree', 'Brian', 'Jacques', 2000, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 345, 'The young haremaid Dotti and the badger-warrior Lord Brocktree—unlikely comrades—set out for Salamandastron together, only to discover the legendary mountain has been captured by the wildcat Ungatt Trunn and his Blue Hordes. To face them, the two must rally an army—hares and otters, shrews and moles, mice and squirrels—and execute a plan that makes up in cleverness what it lacks in force.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1442624011i/99085.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (63, 'Taggerung', 'Brian', 'Jacques', 2001, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 403, 'Years ago, the vermin clan of Sawney Rath kidnapped one of Redwall\'s own-a baby otter, destined to become their \"Taggerung,\" a warrior hero of ancient legend. But as young Tagg grows, he rebels against his destiny. The young otter journeys in search of his birthplace, a member of Sawney\'s clan always near, out to destroy the deserter. With the feisty mouse Nimbalo, Tagg fends off the avenging vermin, but can he find his way back to the Redwall family from whom he was separated so long ago? Here is all of the excitement and adventure a Redwall fan could wish for!', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1429977971i/7976.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (64, 'Triss', 'Brian', 'Jacques', 2002, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 383, 'All her life, Triss the squirrelmaid has suffered the tyranny of the evil ferret king King Agarnu and his daughter, Princess Kurda. But with the help of her fellow slaves, Shogg the otter and Welfo the hedgehog, Triss plans and executes a daring escape by sea. Meanwhile, in Mossflower forest, a new mystery has arisen: a pair of wandering Dibbuns has accidentally discovered what may be the long-lost secret entrance to Brockhall-original home of the warrior badgers. The threads of the story eventually come together when Triss happens upon Redwall in her flight and takes up the famous sword of Martin. The rest is Redwall history.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388786456i/8001.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (65, 'Loamhedge', 'Brian', 'Jacques', 2003, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 388, 'Loamhedge, the deserted Abbey, has been forgotten for countless seasons. What secrets do it\'s ruins hold? When it becomes clear that wheelchair-bound Martha might be cured by a formula buried there, two old warriors are inspired by the spirit of Martin the Warrior himself to go on a quest for the ancient Abbey and three young rebels are determined to go with them. Meanwhile. the giant badger Lonna Bowstripe thirsts for vengeance as he relentlessly pursues Raga Bl and his murdering crew of Searats...who are on their way to attack Redwall itself@ The valiant Abbeybeasts must defend their home, but how can they, when their boldest warriors are away on their quest? Will Redwall fall to vermin invaders at last?', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388437560i/140138.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (66, 'Rakkety Tam', 'Brian', 'Jacques', 2004, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 369, 'A dark force is rampaging through the forests of Mossflower. Gulo the Savage, wolverine, flesh-eater and brutal killer, has come across the seas in search of his brother, Askor. Askor stole the famous walking stone that will make one of them king of the lands of ice and snow - and Gulo wants it back. Anybeast who gets in Gulo\'s way is dead meat. Literally. Rakkety Tam McBurl is a brave border warrior, travelled south in search of adventure. But when his army is attacked by Gulo\'s flesh-eating band, adventure finds him. Gulo is heading for the ancient Redwall Abbey - and Rakkety Tam is determined not to let the savage Gulo destroy the peaceful ways of Redwall.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388437566i/7994.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (67, 'High Rhulain', 'Brian', 'Jacques', 2005, 'Ace Books', 'Tales of Redwall', 0, 'Paperback', 320, 'Tiria Wildlough, a young ottermaid touched by the paw of destiny, embarks on a journey to the mysterious Green Isle, where she joins a band of outlaw otters to rid the land of the villainous Wildcat chieftain Riggu Fellis and his catguard slave masters…', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1326081887i/130352.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (68, 'The Witches of Eileanan', 'Kate', 'Forsyth', 1997, 'Roc Books', 'The Witches of Eileanan', 1, 'Paperback', 411, 'In the Celtic land of Eileanan, witches and magic have been outlawed, and those caught for practicing witchcraft are put to death! It is a land ruled by an evil Queen, where sea-dwelling Fairgean stir, and children vanish in the night. But in a valley deep in the mountains, young Isabeau grows to womanhood under the guidance of an elderly witch, and must set out on a quest, carrying the last hopes of the persecuted witches.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388353334i/264069.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (69, 'The Pool of Two Moons', 'Kate', 'Forsyth', 1998, 'Roc Books', 'The Witches of Eileanan', 2, 'Paperback', 557, 'As Eileanan nears its darkest hour, Meghan must gather rebel forces to move upon the city of Lucescere. There, the Rìgh lies near death, and his Queen, Maya the Ensorcellor, and her babe stand to inherit his power. To end Maya’s brutal reign and bring magic out of the shadows, what was broken must be brought twin sisters who have never met, three parts of an enchanted key, and the winged man with the powers of the lost Lodestar.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1386924963i/264066.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (70, 'The Cursed Towers', 'Kate', 'Forsyth', 1999, 'Roc Books', 'The Witches of Eileanan', 3, 'Paperback', 544, 'The flame-haired twins--Iseult the Scarred Warrior and Isabeau the apprentice-witch--must go their separate ways. Iseult to fight side by side with her husband, Lachlan. Isabeau to the Cursed Towers, to master her powers and to find the family she has never known. One woman battling for a new reign, one woman learning the old ways, their separate threads will twist and turn into a tale of mayhem, mystery, and magic.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388179994i/264067.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (71, 'The Forbidden Land', 'Kate', 'Forsyth', 2000, 'Roc Books', 'The Witches of Eileanan', 4, 'Paperback', 384, 'After her adventures with the League of the Healing Hand, Finn the Cat finds her life at Castle Rurach boring. Snowbound for the winter and faced with the prospect of being molded into “Lady Fionnghal” by her mother, she pines to be on the battlefront with her father against the sea demons. But Finn’s talents are needed elsewhere. Summoned by the Righ, Lachlan the Winged, she must embark on a perilous journey into the Forbidden Land. Imprisoned in the Black Tower is a rebellious prophet whose beliefs have made him an enemy among his own people.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388179990i/264064.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (72, 'The Skull of the World', 'Kate', 'Forsyth', 2001, 'Roc Books', 'The Witches of Eileanan', 5, 'Paperback', 363, 'In the land of Eileanan, the Pact of Peace has not meant the end of unrest. And, though Isabeau would like to return home to help her family in these uncertain times, she must first venture to the Skull of the World where she will discover her true talents as a witch. And when she does return home, she does so transformed with the power to overcome her family\'s enemies once and for all.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388180004i/264065.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (73, 'The Fathomless Caves', 'Kate', 'Forsyth', 2002, 'Roc Books', 'The Witches of Eileanan', 6, 'Paperback', 368, 'In Eileanan, victory has finally been won, and those of faery kind--from the mighty dragons to the mysterious nyx--have sworn their friendship and aid. Only the sea-dwelling Fairgean have refused to sign the Pact of Peace. Driven by ancient hatreds, they have devoted themselves to destroying all who dwell upon the land.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388179989i/264068.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (74, 'The Tower of Ravens', 'Kate', 'Forsyth', 2005, 'Roc Books', 'Rhiannon\'s Ride', 1, 'Paperback', 429, 'One-Horn\'s daughter is not like the others of her kind. Born of a human father, she lacks the horns so prized by her people and is scorned even by her own mother. Her only chance for escape is to capture one of the legendary flying horses and ride it to freedom.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388231338i/28799.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (75, 'The Shining City', 'Kate', 'Forsyth', 2006, 'Roc Books', 'Rhiannon\'s Ride', 2, 'Paperback', 522, 'Rhiannon, a wild and fierce half-human girl, tamed a winged horse to escape the vicious satyricorn tribe who raised her. In the human world, the handsome apprentice-witch Lewen has convinced her to stay with him and learn to use her strong magical talents. But before her training can commence, Rhiannon must answer for a past crime in…', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388353334i/28798.jpg');
INSERT INTO `book` (`id`, `title`, `author_first_name`, `author_last_name`, `publish_year`, `publisher`, `Series`, `occurrence_in_series`, `medium`, `number_of_pages`, `synopsis`, `book_cover`) VALUES (76, 'The Heart of Stars', 'Kate', 'Forsyth', 2007, 'Roc Books', 'Rhiannon\'s Ride', 3, 'Paperback', 414, 'An evil necromancer has kidnapped the princess Olywynne and her twin brother, plotting to spill their blood-for revenge, and to restore his own family to life. Chaos reigns in the capital, and no one can stop the necromancer but Rhiannon and her winged mare. But can she bring herself to rescue the woman she hates more than anyone-Olywynne, her rival for the apprentice-witch Lewen\'s love-especially when she stands to lose everything she holds dear in the effort?', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388237993i/28797.jpg');

COMMIT;

